# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: 'ko-KR'

reviews:
  auto_review: true # 자동 리뷰 활성화 또는 비활성화
  review_status: true # 리뷰 상태 메시지 표시 또는 숨기기
  base_branch: dev # 리뷰의 기본 브랜치 설정
  profile: 'chill'
  poem: true

commands:
  pause: true # 리뷰 일시 중지 허용
  resume: true # 리뷰 재개 허용
  review: true # 증분 리뷰 활성화
  full_review: true # 전체 리뷰 활성화
  summary: true # 요약 생성 활성화
  generate_docstrings: true # 도크스트링 생성 활성화 (베타)
  resolve: true # 모든 CodeRabbit 리뷰 코멘트 해결 허용
  configuration: true # 현재 설정 표시
  help: true # 도움말 명령 활성화

ignore_keywords:
  - '@coderabbitai ignore' # 특정 PR이 리뷰되지 않도록 하는 키워드

summary_keywords:
  - '@coderabbitai summary' # 고수준 요약을 생성하는 키워드

title_keywords:
  - '@coderabbitai' # 제목을 자동으로 생성하는 키워드

# 필요에 따라 추가 설정 옵션을 여기에 추가할 수 있습니다
chat:
  auto_reply: true
